### ISSUE TITLE
Wrong Commit

### ISSUE THREAD

**Issue by alikouhfar** [ShayanTheNerd/IP-address-tracker#1]
سلام
من وقتی پروژه شما رو کلون کردم، متوجه شدم محتوای پروژه هیچ ارتباطی به اسم repository نداره و مثل اینکه قبلن همچین پروژه‌ای رو push کردی. احساس میکنم موقع push کردن خطا زدی و پروژه اشتباهی رو داخل این repository فرستادی

**Comment by ShayanTheNerd** [comment]
Hi, thanks for taking the time to submit an issue.
Actually, it _is_ a new project and since the structure was similar to an old one, I decided to go on and use its template as a starting point. So, that's why the content doesn't match up with the name of the repository, yet. I should've kept it as a private repository until the basic, required changes are made and that's what I'm going to do.
